### ISSUE TITLE
UNABLE TO USE RTMP

### ISSUE THREAD

**Issue by tsromana** [esxbr/ustvnow-m3u-server#3]
hey is there a way to use the http stream as i am unable to use rtmp to play in vlc, but if i manually get http url from ustv website it works fine, the token generation and everything is working good, can i change something in the code to get http streams.

**Comment by esxbr** [comment]
The vlc is able to play rtmp.
Did you try opening the channels.m3u (http://SERVER_IP:8787/channels.m3u?u=EMAIL&p=PASSWORD http://server_ip:8787/channels.m3u?u=EMAIL&p=PASSWORD) and than play any channel?

**Comment by tsromana** [comment]
yupp it gives out a rtmp stream which doesn't work but when i use the token generated in a http steam it works good

**Comment by tsromana** [comment]
http://lv7.ustvnow.com/dvrtest/smil:xxxxxxxxxxxxxxx/playlist.m3u8?key=xxxxxxxxxxxxxxxxxxxxxxx 
url like this works good

**Comment by tsromana** [comment]
so after alot of struggle i guess i have found the issue the server uses lv2.ustvnow domain but the my ustvnow profile only works with lv7 and lv9.ustvnow domain can  that be a issue, changing the base url breaks the server
