### ISSUE TITLE
Stream URL not working

### ISSUE THREAD

**Issue by A-Duck** [esxbr/ustvnow-m3u-server#8]
I'm having issues getting this script to work, I've tried the script from the original repository as well as all of the forks and have tried running them with python and python2.7
Usually the channels will be listed 3 times with no current information and the EPG will be filled but the stream won't start playing. If i use the guilleiguaran fork the channels will load once as they should, the EPG is filled and the channel info is loaded sometimes but again the stream won't play.
I've tried opening the stream with VLC but i get an input/output error.
Has something changed with the website that this doesnt work anymore or is there just something wrong with my implementation?
I'm running Ubuntu 16.04

Script Log: http://pastebin.com/vgaCXUnh
Kodi Log: http://pastebin.com/xFxbwisk

**Comment by AgileHumor** [comment]
No, the channel links have not worked for some time in my testing.

I'm using this for the M3U file with working links: https://github.com/mathsgrinds/ustvnow-iptv-m3u-playlist

I still use this project for the XMLTV (which does work).  Hopefully this project stream channels will work again so I can have a single solution to manage for M3U and XMLTV.

**Comment by ctilluma** [comment]
I've forked this project. It works for guides and channels. Let me know if you have any issues.
https://github.com/ctilluma/ustvnow-m3u-server
